#!/usr/bin/env groovy

@Library('DRC_Global_Pipeline_Libraries@master')

IS_DEV = true
ACCOUNT_NUM = null

def credentials = drc_AwsAssumeRoleAsEnv([
  [account_number: '911870898277', region: 'us-east-2'],
  [account_number: '333509430799', region: 'us-east-2']
])

pipeline {
  environment {
    WORKING_DIR = "backend"
    APP_NAME = 'Zulip'
    REGION = 'us-east-2'
  }
  agent {
    kubernetes(
      drc_k8_agent(templates: [
        [name: 'terraform', isDefault: true]
      ])
    )
  }

  options {
    buildDiscarder(logRotator(daysToKeepStr: '3', artifactDaysToKeepStr: '3'))
    ansiColor('xterm')
  }

  parameters {
    choice(choices: ['dev', 'prod'], description: 'Deploy to le or prod?', name: 'ENVIRONMENT')
    choice(choices: [true, false], description: 'Dry run (tf plan) or deploy (tf apply)?', name: 'DRYRUN')
  }

  stages {
    stage ('Configure') {
      steps {
        script {
          if (params.ENVIRONMENT == 'prod') {
            IS_DEV = false
            ACCOUNT_NUM = '911870898277'
          } else {
            IS_DEV = true
            ACCOUNT_NUM = '333509430799'
          }
          println(IS_DEV)
        }
      }
    }
    stage ('Dev') {
      when {
        expression { IS_DEV }
      }
      steps {
        withEnv(credentials['333509430799']) {
          dir("${WORKSPACE}/${env.WORKING_DIR}") {
            script {
              sh 'aws sts get-caller-identity'
              sh "make plan env=${params.ENVIRONMENT}"
              if(can_deploy([name: "dev", dry_run: params.DRYRUN, region: env.REGION, account_num: ACCOUNT_NUM])) {
                sh "make apply env=${params.ENVIRONMENT}"
              }
            }
          }
        }
      }
    }
    stage ('Prod') {
      when {
        expression { !IS_DEV }
      }
      steps {
        script {
          withEnv(credentials['911870898277']) {
            dir("${WORKSPACE}/${env.WORKING_DIR}") {
              script {
                sh 'aws sts get-caller-identity'
                sh "make plan env=${params.ENVIRONMENT}"
                if(can_deploy([name: "prod", dry_run: params.DRYRUN, region: env.REGION, account_num: ACCOUNT_NUM])) {
                  sh "make apply env=${params.ENVIRONMENT}"
                }
              }
            }
          }
        }
      }
    }
  }
}

def can_deploy(def tier) {
  def result = 'SUCCESS'

  if(tier.dry_run == 'false') {
    result = drc_AskForPermissionSkip([
      name     : "Deploy ${env.APP_NAME} ${tier.region} to ${tier.name}",
      to_time  : 10,
      to_unit  : 'MINUTES',
      id       : "${env.APP_NAME}-${tier.region}",
      message  : "Deploy ${env.APP_NAME} ${tier.region} to ${tier.name} or abort?",
      submitter: "pnambiar,grees,nkovalenko,bpoush,tjensen,atormanen,jwdunn"
    ])
  }

  if (result == 'ABORTED') {
    println('pipeline aborted')
    currentBuild.result = 'ABORTED'
    error("Aborting the build.")
  } else if (result == 'SKIPPED') {
    println('SKIP')
  } else {
    println("${tier.name} ${region}")
    if (tier.dry_run == 'false') {
      return true
    }
  }
  return false
}
