# Generated by Django 4.1.7 on 2024-02-15 22:18

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0422_multiuseinvite_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpresence",
            name="heartbeat_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=True,
        ),
    ]
