# Generated by Django 5.0.7 on 2024-10-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0423_userpresence_heartbeat_timestamp"),
        ("zerver", "0576_backfill_imageattachment"),
    ]

    operations = []
